In [16]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix
from sklearn.metrics import classification_report
import joblib

In [17]:
url = 'https://raw.githubusercontent.com/IBM/telco-customer-churn-on-icp4d/master/data/Telco-Customer-Churn.csv'
df = pd.read_csv(url)
df.head()

,customerID,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges,Churn
0,7590-VHVEG,Female,0,Yes,No,1,No,No phone service,DSL,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85,No
1,5575-GNVDE,Male,0,No,No,34,Yes,No,DSL,Yes,...,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5,No
2,3668-QPYBK,Male,0,No,No,2,Yes,No,DSL,Yes,...,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15,Yes
3,7795-CFOCW,Male,0,No,No,45,No,No phone service,DSL,Yes,...,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75,No
4,9237-HQITU,Female,0,No,No,2,Yes,No,Fiber optic,No,...,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65,Yes

In [18]:
# df.shape
# df.info()
# df.columns
df["Churn"].value_counts()

Churn
No     5174
Yes    1869
Name: count, dtype: int64

In [19]:
x = df.drop(['Churn', 'customerID'], axis=1)
y = df['Churn']

x.head()
# y.head()
# x.dtypes

,gender,SeniorCitizen,Partner,Dependents,tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,OnlineBackup,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,MonthlyCharges,TotalCharges
0,Female,0,Yes,No,1,No,No phone service,DSL,No,Yes,No,No,No,No,Month-to-month,Yes,Electronic check,29.85,29.85
1,Male,0,No,No,34,Yes,No,DSL,Yes,No,Yes,No,No,No,One year,No,Mailed check,56.95,1889.5
2,Male,0,No,No,2,Yes,No,DSL,Yes,Yes,No,No,No,No,Month-to-month,Yes,Mailed check,53.85,108.15
3,Male,0,No,No,45,No,No phone service,DSL,Yes,No,Yes,Yes,No,No,One year,No,Bank transfer (automatic),42.30,1840.75
4,Female,0,No,No,2,Yes,No,Fiber optic,No,No,No,No,No,No,Month-to-month,Yes,Electronic check,70.70,151.65

Converting dtype of TotalCharges from object to numeric

In [20]:
x['TotalCharges'] = pd.to_numeric(x['TotalCharges'], errors = 'coerce')
# x["TotalCharges"].isnull().sum()
# x[x["TotalCharges"].isnull()]
# x["TotalCharges"].dtype
x[x["TotalCharges"].isnull()][["tenure", "MonthlyCharges", "TotalCharges"]]

      tenure  MonthlyCharges  TotalCharges
488        0           52.55           NaN
753        0           20.25           NaN
936        0           80.85           NaN
1082       0           25.75           NaN
1340       0           56.05           NaN
3331       0           19.85           NaN
3826       0           25.35           NaN
4380       0           20.00           NaN
5218       0           19.70           NaN
6670       0           73.35           NaN
6754       0           61.90           NaN

To fill values for Null columns from NaN --> 0

In [21]:
x['TotalCharges'] = x['TotalCharges'].fillna(0)

Convert Y (Churn) from yes/no --> 0/1

In [22]:
y = y.map({'Yes' : 1, 'No' : 0})
y.head()

0    0
1    0
2    1
3    0
4    1
Name: Churn, dtype: int64

one-hot Encoding

In [23]:
x = pd.get_dummies(x, drop_first=True)
x.head()

,SeniorCitizen,tenure,MonthlyCharges,TotalCharges,gender_Male,Partner_Yes,Dependents_Yes,PhoneService_Yes,MultipleLines_No phone service,MultipleLines_Yes,...,StreamingTV_No internet service,StreamingTV_Yes,StreamingMovies_No internet service,StreamingMovies_Yes,Contract_One year,Contract_Two year,PaperlessBilling_Yes,PaymentMethod_Credit card (automatic),PaymentMethod_Electronic check,PaymentMethod_Mailed check
0,0,1,29.85,29.85,False,True,False,False,True,False,...,False,False,False,False,False,False,True,False,True,False
1,0,34,56.95,1889.50,True,False,False,True,False,False,...,False,False,False,False,True,False,False,False,False,True
2,0,2,53.85,108.15,True,False,False,True,False,False,...,False,False,False,False,False,False,True,False,False,True
3,0,45,42.30,1840.75,True,False,False,False,True,False,...,False,False,False,False,True,False,False,False,False,False
4,0,2,70.70,151.65,False,False,False,True,False,False,...,False,False,False,False,False,False,True,False,True,False

Splitting data for train and test

In [24]:
x_train, x_test, y_train, y_test = train_test_split(x,y, test_size=0.2, random_state=42)
y_train.shape

(5634,)

Scaling the data

In [25]:
scaler = StandardScaler()
x_train = scaler.fit_transform(x_train)
x_test = scaler.transform(x_test)

Logistic regression

In [26]:
model = LogisticRegression()
model.fit(x_train, y_train)

LogisticRegression()

In [27]:
y_pred = model.predict(x_test)
y_pred[:5]

array([1, 0, 0, 1, 0])

Accuracy of the prediction

In [28]:
accuracy = accuracy_score(y_test, y_pred)
# print("Accuracy :",accuracy)


# print(y_test.shape)
# print(y_pred.shape)
# print((y_test.values == y_pred).sum())

# print(y_test.value_counts())
# print(pd.Series(y_pred).value_counts())
# print(model.score(x_test, y_test))
# "Churn" in x.columns
# print(x.shape)
# print(y.shape)
# print(y.value_counts())
# print(model.coef_)
# print(confusion_matrix(y_test, y_pred))

y_prob = model.predict_proba(x_test)
y_prob[:5]

array([[0.30646608, 0.69353392],
       [0.93871374, 0.06128626],
       [0.99553173, 0.00446827],
       [0.3927911 , 0.6072089 ],
       [0.99418071, 0.00581929]])

Classification report

In [29]:
print(classification_report(y_test, y_pred))

joblib.dump(model, "churn_model.pkl")

              precision    recall  f1-score   support

           0       0.86      0.90      0.88      1036
           1       0.69      0.60      0.64       373

    accuracy                           0.82      1409
   macro avg       0.77      0.75      0.76      1409
weighted avg       0.81      0.82      0.82      1409

['churn_model.pkl']

Sample Prediction

In [30]:
sample = x_test[0].reshape(1, -1)

prediction = model.predict(sample)
probability = model.predict_proba(sample)

print("Prediction:", prediction[0])
print("Churn Probability:", probability[0][1])

Prediction: 1
Churn Probability: 0.6935339178419516